### ISSUE TITLE
loader vs module key

### ISSUE THREAD

**Issue by jjpe** [ballercat/wasm-loader#11]
The example in the README.md of this project states that the following should be used to include the wasm loader:

```
  loaders: [
    {
      test: /\.wasm$/,
      loaders: ['wasm-loader']
    }
  ]
```

However, the webpack website itself says that another format must be used to include loaders:
```
 module: {
    rules: [
      { test: /\.txt$/, use: 'raw-loader' }
    ]
  }
```

So I'm confused now. Which one is correct, and why?

**Comment by PaulRBerg** [comment]
This library is relatively old and still uses webpack v1. Read more about the differences between the various versions of webpack in [this thread](https://stackoverflow.com/questions/43002099/rules-vs-loaders-in-webpack-whats-the-difference).

You might want to take a look at the official [webpack example for wasm](https://github.com/webpack/webpack/tree/master/examples/wasm-simple).

**Comment by ballercat** [comment]
I wrote this around Webpack ~v3 but yes, please use native Webpack 5 WebAssembly support. Here's a small demo https://github.com/ballercat/minimal-webpack5-wasm-demo
