### ISSUE TITLE
Fails for modules that are larger than 4K

### ISSUE THREAD

**Issue by cimi** [ballercat/wasm-loader#4]
Trying to load larger modules fails in Chrome 59:

> WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.

This seems to be because the [loading is synchronous](https://stackoverflow.com/questions/45284788/webassembly-compile-is-disallowed-on-the-main-thread-if-the-buffer-size-is-larg/45285081#45285081):

```
src/wasm/counter.wasm:13
  10 | let wa;
  11 | const make = source => {
  12 |   // buffer should already be set
> 13 |   return wa = new Module(buffer);
  14 | };
  15 | 
  16 | const WebAssemblyModule = function(deps = {
```

**Comment by ballercat** [comment]
Ah yeah. This thing needs to be promisified. I'll patch it up soon. Thanks!

**Comment by ballercat** [comment]
The fix is in master, thanks again for pointing it out. I'll publish new version to npm tomorrow. 

I din't have a 4k+ module laying around but it should work fine now. Closing this.
