### ISSUE TITLE
Streaming Instantiate support

### ISSUE THREAD

**Issue by ballercat** [ballercat/wasm-loader#6]
# Goal
Allow for full WebAssembly API.

# Overview
An engineer should be able to stream their module into the bundle if necessary. 

# Acceptance Criteria

- [ ] Make a unit test, be creative.
- [ ] Make tests pass

**Comment by TheLarkInn** [comment]
I think @sokra mentioned to me that just returning the buffer would work for webpack 4.

**Comment by ballercat** [comment]
mindblown.gif

Will definitely give that a shot.

**Comment by xtuc** [comment]
@TheLarkInn that sounds awesome but are you sure you talk about WebAssembly.instantiateStreaming? That sounds strange to me since Webpack is language/platform agnostic for loaders, right?

**Comment by sokra** [comment]
sean is talking about using the native WASM support in webpack 4, which is using streaming compilation, when available.

**Comment by xtuc** [comment]
I just noticed that `WebAssembly.compileStreaming` and `WebAssembly.instantiateStreaming` are flagged as an experimental technology. I guess we'll need to wait for a bit before actually using it?

**Comment by crossle** [comment]
Hope support instantiateStreaming
