### ISSUE TITLE
how to load 3rd party .wasm

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [ballercat/wasm-loader#9]
Please i'm trying to load this 3rd party .wasm file following your documentation.
> http://www.datasymbol.com/barcode-web-sdk/web-sdk-assembly.html

I get stuck at this error: 

`counter:1 Uncaught (in promise) LinkError: WebAssembly Instantiation: Import #0 module="env" function="DYNAMICTOP_PTR" error: global import must be a number`

this is the code i'm using:

```
<script>
import scanner from './scanner.wasm'

export default {
  data() {
    return {}
  },
  mounted() {
    console.log('loading scanner...')

    scanner({
      global: {},
      env: {
        memoryBase: 0,
        tableBase: 0,
        memory: new WebAssembly.Memory({ initial: 256, limit: 1000 }),
        table: new WebAssembly.Table({ initial: 0, element: 'anyfunc' })
      }
    }).then(obj => {
      // obj.InitLib(null)
    })
```

not sure what i'm doing wrong?

**Comment by xtuc** [comment]
This is an error from the browser, the global import has the wrong type. 

 You need to use something like:
```js
scanner({
      global: 0, // number here
      env: {
        memoryBase: 0,
        tableBase: 0,
        memory: new WebAssembly.Memory({ initial: 256, limit: 1000 }),
        table: new WebAssembly.Table({ initial: 0, element: 'anyfunc' })
      }
    })
```

**Comment by xtuc** [comment]
If it's ok for you now, could you please close this issue?
